[toolchain]
solana_version = "1.18.26"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pnft_mortgage_market = "C2kfwjLdi7uJjfNeE25MYqviPcvSokwpxRyrrhYaGCf6"

[programs.devnet]
pnft_mortgage_market = "C2kfwjLdi7uJjfNeE25MYqviPcvSokwpxRyrrhYaGCf6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
